---
- hosts: mgmt-k8s-master, mgmt-k8s-worker
  become: yes
  tasks:
    - name: install docker package
      command: apt -y install docker.io apt-transport-https

    - name: remove old daemon.json
      command: rm -rf /etc/docker/daemon.json

    - name: create docker daemon.json
      file:
        path : "/etc/docker/daemon.json"
        state: "touch"

    - name: config daemon.json
      blockinfile:
        path: "/etc/docker/daemon.json"
        marker: ""
        block: |
                {
                 "exec-opts": ["native.cgroupdriver=systemd"],
                 "log-driver": "json-file",
                 "log-opts": {
                 "max-size": "100m"
                 },
                 "storage-driver": "overlay2"
                }
    - name: Remove blank lines blockinfile put in
      lineinfile :
        path: "/etc/docker/daemon.json"
        state: absent
        regexp: '^$'
    
    - name: start and enable docker service
      shell : |
              systemctl restart docker
              systemctl enable --now docker

    - name: create kubernetes sysctl file
      file:
        path: "/etc/sysctl.d/k8s.conf"
        state: "touch"

    - name: config kubernetes sysctl file
      blockinfile:
        path: "/etc/sysctl.d/k8s.conf"
        block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1

    - name: update sysctl config
      command: sysctl --system

    - name: disable swap
      shell: |
              swapoff -a
              sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: add kubernetes repo file
      shell: |
              curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
              echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
              apt update -y

    - name: install kubeadm kubelet kubectl
      command: apt -y install kubeadm kubelet kubectl
 

