#Ansible-playbook install k8s
---
- hosts: "dr-k8s-master, dr-k8s-worker"
  remote_user: compnet
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
          - name: Uninstall CRI-O
            command : dnf -y remove cri-o cri-tools podman buildah
