- name: partitioning
  hosts: all
  tasks:
    - name: create partition
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        part_end: 2GiB
        state: present

- name: lvm-part-1
  hosts: all
  tasks:
    - name: create volume group
      lvg:
        vg: vg0
        pvs: /dev/sdb1
      when: ansible_devices.sdb.partitions.sdb1 is defined
- name: lvm-part-2
  hosts: all
  tasks:
    - name: create logical volume
      lvol:
        vg: vg0
        lv: lv0
        size: 1500m
      when: ansible_lvm.vgs.vg0 and ((ansible_lvm.vgs.vg0.size_g | float)>1.5)

    - name: send message if storage not enough
      debug:
        msg: Not enough space for create logical volume
      when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float)<1.5)

    - name: create smaller logical volume
      lvol:
        vg: vg0
        lv: lv0
        size: 800m
      when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float)<1.5)

- name: lvm-part-3
  hosts: all
  tasks:
    - name: formating logical volume as xfs
      filesystem:
        dev: /dev/vg0/lv0
        fstype: xfs
      when: ansible_lvm.lvs.lv0 is defined
